-- Criação da tabela CLIENTES e inserção de dados de exemplo
CREATE TABLE CLIENTES (
    ID NUMBER PRIMARY KEY,
    NOME VARCHAR2(100),
    CIDADE VARCHAR2(100)
);

-- Sequence para autoincremento
CREATE SEQUENCE SEQ_CLIENTES START WITH 4 INCREMENT BY 1;

-- Trigger para atribuir o próximo valor da sequence
CREATE OR REPLACE TRIGGER TRG_CLIENTES_BI
BEFORE INSERT ON CLIENTES
FOR EACH ROW
BEGIN
  IF :NEW.ID IS NULL THEN
    SELECT SEQ_CLIENTES.NEXTVAL INTO :NEW.ID FROM DUAL;
  END IF;
END;
/

INSERT INTO CLIENTES (ID, NOME, CIDADE) VALUES (1, 'Marcus Vinicius', 'Goiânia');
INSERT INTO CLIENTES (ID, NOME, CIDADE) VALUES (2, 'Ana Paula', 'Brasília');
INSERT INTO CLIENTES (ID, NOME, CIDADE) VALUES (3, 'Carlos Alberto', 'São Paulo');
COMMIT;
